= perftest - performance of various shell and scripting languages

Patterned after a shorter comparison in
https://learningtree.com/396[Learning Tree Course 396, Unix Tools & Utilities].

== Broken!

This depends on the original BSD version of the time command; I will either add 
that here, or change the report gatherer to adapt to other variants of "time".

== Pre-requisites

You need to install a Java SDK ("JDK"). The current release is Java 22, but
any release of JDK 11 or later should suffice.

Using your system's package manager, install as many Awk implementations as
you can find - gawk hawk mawk nawk are the most likely ones.

== Before you run

There are two sets of tests in the variable PROGS in the runall script.
The first one is the full one; the second is a shorter one (omitting the
slowest tests) for testing, mainly used when modifying the base package
(i.e., for normal use you want the full one). Edit runall to un-comment
the one you want.

== Running

Just type `make`. The results will be displayed, and also recorded in 
the file "results".

If you don't have `make` installed, just do `sh runall` and either
redirect or `tee` the output if you want it saved to a file;
`report` is the customary filename for the output.
