#!/bin/sh

# extract the results from make output

# recommended to run "make" instead of this script directly

awk '
$2=="small"{
	small[$1] = $3
	}
$2=="medium"{
	medium[$1] = $3
	}
$2=="large"{
	large[$1] = $3
	}
END {
	printf "%-12s\t\t%6s\t\t%6s\t\t%6s %s\n", "Language", "2k", "18k", "500k", "(sort col)"
	for (prog in small) {
		printf "%-12s\t\t%6.2f\t\t%6.2f\t\t%6.2f\n", prog, small[prog], medium[prog], large[prog]
	}
}' $* |sort -rn -k4
